CREATE DATABASE DemoDB
GO 


USE DemoDB
GO 

SELECT IsOptimizedLockingOn = DATABASEPROPERTYEX(DB_NAME(), 'IsOptimizedLockingOn');

ALTER DATABASE DemoDB 
SET ACCELERATED_DATABASE_RECOVERY = ON;
GO 

ALTER DATABASE DemoDB 
	SET OPTIMIZED_LOCKING = ON;
	GO 



USE DemoDB
GO 

SELECT IsOptimizedLockingOn = DATABASEPROPERTYEX(DB_NAME(), 'IsOptimizedLockingOn');